packages:
  - 'packages/*'
  - 'apps/*'
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
minimumReleaseAgeExclude:
  - esbuild@0.24.3
  - vite@6.4.2
overrides:
  esbuild@<=0.24.2: ^0.24.3
  vite@<=6.4.1: ^6.4.2
