name: Release

on:
  push:
    branches:
      - create_pr

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN_PUBLIC }}
  FORCE_COLOR: '3'

jobs:
  release:
    name: Create Release PR
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Generate token
        id: auth
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ secrets.AUTH_APP_ID }}
          private-key: ${{ secrets.AUTH_APP_KEY }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v5
        with:
          dest: ${{ runner.temp }}/setup-pnpm

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Prepare data for badges
        run: |
          pnpm --filter @localazy/cdn-client run build
          pnpm --filter @localazy/cdn-client run test:coverage
          echo "BADGES_COVERAGE=$(node -e 'process.stdout.write(String(require("./packages/cdn-client/coverage/coverage-summary.json").total.lines.pct))')" >> "$GITHUB_ENV"
          echo "BADGES_SIZE=$(gzip -c packages/cdn-client/dist/browser/localazy-cdn-client.umd.min.js | wc -c)" >> "$GITHUB_ENV"

      - name: Run release script
        run: npx @localazy/workflow-scripts@latest create-release-pr packages/cdn-client
        env:
          GITHUB_TOKEN: ${{ steps.auth.outputs.token }}
